### ISSUE TITLE
feature request: Feature map

### ISSUE THREAD

**Issue by y-nk** [lukeshay/astro-aws#111]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

When running the adapter on Astro@3, the message shows at dev:

```
[astro] The adapter @astro-aws/adapter doesn't provide a feature map. From Astro 3.0, an adapter can provide a feature map. Not providing a feature map will cause an error in Astro 4.0.
```

### Describe the solution you'd like

We need to add a feature map to the adapter so that Astro doesn't complain.

### Describe alternatives you've considered

Add an empty feature map to silence the error

**Comment by lukeshay** [comment]
The adapter does provide a feature map unless Astro changed how it works. Are you using the latest version of `@astro-aws/adapter`?

**Comment by y-nk** [comment]
@lukeshay i'm still at 0.3, i'll update to 0.5. thanks for publishing new releases so fast 🙏
