### ISSUE TITLE
[Bug]: @astro-aws/adapter → can't build with astro v4

### ISSUE THREAD

**Issue by y-nk** [lukeshay/astro-aws#119]
### 💻

- [ ] Would you like to work on a fix?

### Input code

I'm building in `output: 'hybrid'` with the latest `astro@4.0.7` using the `@astro-aws/adapter@0.5.0` and there's some issue with esbuild configuration.

At the end of the process, the log shows:

```
17:18:41
 finalizing server assets

17:18:41 [build] Rearranging server assets...
✘ [ERROR] No loader is configured for ".node" files: node_modules/sharp/build/Release/sharp-darwin-arm64v8.node

    node_modules/sharp/lib/sharp.js:10:27:
      10 │   module.exports = require(`../build/Release/sharp-${platformAndArch}.node`);
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve require("../vendor/**/*/**/*/versions.json")

    node_modules/sharp/lib/utility.js:58:21:
      58 │   versions = require(`../vendor/${versions.vips}/${platformAndArch}/versions.json`);
         ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

No loader is configured for ".node" files: node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
  Stack trace:
    at failureErrorWithLog (~/node_modules/esbuild/lib/main.js:1650:15)
    at ~/node_modules/esbuild/lib/main.js:1003:52
    at ~/node_modules/esbuild/lib/main.js:1085:16
    at handleIncomingPacket (~/node_modules/esbuild/lib/main.js:763:9)
    at Socket.emit (node:events:513:28)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Current and expected behavior

It should be possible to build.

### Environment

1. Apple Silicon (M2)
2. `astro@4.0.7` (comes with forced `sharp` installation)
3. `@astro-aws/adapter@0.5.0`

### Possible solution

For now, revert to astro@3 (afaik)

### Additional context

I'm going to have a look at esbuild config after filing this ticket, maybe i can have my way with the adapter's options.

**Comment by y-nk** [comment]
So far the only quick win is to remove sharp from esbuild. add `external: ["sharp"]` in `esbuildOptions`. I'm thinking this should be a default + some warn shout out if it's really not supported as suggested by #93 and #94.

**Comment by lukeshay** [comment]
Yeah these packages does support sharp or schoop yet. See #93 and #94

**Comment by y-nk** [comment]
@lukeshay i'm surprised of why it's not supported since it looks ok to use (at least) sharp to lambda, even at edge ([see this](https://medium.com/@shivamgrg38/dynamic-image-resizing-and-formatting-with-aws-lambda-edge-and-sharp-39c98214c7cc))

is it just a bundler issue?
