### ISSUE TITLE
Website link on Astro is not working

### ISSUE THREAD

**Issue by Mansi1** [lukeshay/astro-aws#138]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I was searching for an adapter to aws and i found this awesome project please update the website here https://astro.build/integrations/?search=astro-aws%2Fadapter.

I will checkout this project and maybe if its possible i can help to write documentation how to use it.

<img width="1267" alt="image" src="https://github.com/lukeshay/astro-aws/assets/12079044/1f8f6bc6-43a7-4447-9932-435f41a25ee5">

### Describe the solution you'd like

Redirect it to do [www.docs.astro-aws.org/](https://www.docs.astro-aws.org/)

### Describe alternatives you've considered

-_-

**Comment by Mansi1** [comment]
Sorry for that feature request i didnt know where to add !!

**Comment by lukeshay** [comment]
Fixed
