### ISSUE TITLE
Query parameters not getting passed to Lambda

### ISSUE THREAD

**Issue by ShivamJoker** [lukeshay/astro-aws#48]
### 💻

- [X] Would you like to work on a fix?

### Input code

Source for astro and CDK - https://github.com/LearnAWS-io/Open-Quotes-Website

### Current and expected behavior

Search query params doesn't get passed to the lambda.

URL - https://d2cwgta0kas6xp.cloudfront.net/?lastQuote=0f2mA4u1p3E0eqqsDRZuLgxHuHH

Cloudwatch logs:
```
2023-03-04T10:39:39.240Z	4f3aac49-fe22-4492-9758-2e313559f253	INFO	firstQuoteId null
2023-03-04T10:39:39.240Z	4f3aac49-fe22-4492-9758-2e313559f253	INFO	lastQuoteId null
```
Also I have disabled the caching

`CachePolicy.CACHING_DISABLED`

### Environment

  Astro
    "@astro-aws/adapter": "^0.3.0",
    "astro": "^2.0.17"

CDK
    "@astro-aws/constructs": "^0.3.0",
    "aws-cdk-lib": "2.67.0",
    "cdk-iam-floyd": "^0.485.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.21"

**Comment by lukeshay** [comment]
Have you tried creating a cache policy that passes all query params?

**Comment by ShivamJoker** [comment]
What will the config look like?

**Comment by ShivamJoker** [comment]
Ok I created cache policy which passes the specific query params, It seems to solve the issue.

@lukeshay can we have the default config with `allowAll()` so that when using the package people don't struggle?

Here is the full code:

```js
const cachePolicy = new CachePolicy(this, "quote-app-cache-policy", {
  maxTtl: Duration.days(365),
  minTtl: Duration.seconds(5),
  defaultTtl: Duration.minutes(10),

  queryStringBehavior: CacheQueryStringBehavior.allowList(
    "firstQuote",
    "lastQuote",
    "refresh"
  ),
});

const astroAws = new AstroAWS(this, "quotes-app", {
  websiteDir: "../",
  output: "server",
  cdk: {
    cloudfrontDistribution: {
      defaultBehavior: {
        cachePolicy: cachePolicy,
      },
    },
    lambdaFunction: {
      environment: {
        TABLE_NAME: quotesDbTable.tableName,
      },
    },
  },
});

```

**Comment by lukeshay** [comment]
Yeah I will update it to have a more lenient cache policy

**Comment by lukeshay** [comment]
The default cache policy provided by AWS does not include query strings. For now, I am only configuring the infrastructure that needs to be. This could change in the future but for now, this issue will not be prioritized.
