### ISSUE TITLE
[Bug]: @astro-aws/adapter types not properly exported/packaged

### ISSUE THREAD

**Issue by firxworx** [lukeshay/astro-aws#88]
### 💻

- [ ] Would you like to work on a fix?

### Input code

In `astro.config.mjs` with type-checking by typescript try importing the adapter:

```js
// @ts-check

import aws from '@astro-aws/adapter'
```

### Current and expected behavior

TypeScript complains: "Cannot find module '@astro-aws/adapter' or its corresponding type declarations.ts(2307)"

Workaround:

```js
// @ts-expect-error -- package does not correctly export and package types for the default import
Cannot find module '@astro-aws/adapter' or its corresponding type declarations.ts(2307)
```

Having types is nice especially with an unfamiliar package that doesn't have a lot of documentation yet.

I can see there are `.d.ts` files within the `node_modules/@astro-aws/adapter` folder however there seems to be an issue.

I made sure to restart my TS server and then full-on VSCode prior to reporting this issue and it still persists.

### Environment

- "@astro-aws/adapter": "^0.4.0"
- "astro": "^3.1.2"
- pnpm 8.7.4
- node 18.17.1
- cdk version not applicable to this issue

### Possible solution

Not 100% sure as I don't use turborepo, plus I do see `.d.ts` files in the package...

However I will note that the config option for ensuring types are emitted for a package is ensuring that `declaration: true`  in `tsconfig.json`.

I do not see this in https://github.com/lukeshay/astro-aws/blob/main/tsconfig.base.json which both `tsconfig.json` and `tsconfig.build.json` in `packages/adapter` extend from.

TypeScript docs: https://www.typescriptlang.org/tsconfig#declaration
You may also want to consider `declarationDir` to organize where the type files are placed.

**Comment by lukeshay** [comment]
Can you share the repo that you are running into this error in?
