### ISSUE TITLE
Support providing Astro.locals through the adapter

### ISSUE THREAD

**Issue by Csszabi98** [lukeshay/astro-aws#96]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

The first party astro node adapter supports providing Astro.locals when ran in middleware mode. It would be convinient to implement it for the aws adapter as well to enable easily passing data from the handler to Astro.

https://docs.astro.build/en/guides/middleware/

### Describe the solution you'd like

Add a new optional parameter that enables supplying Astro.locals

### Describe alternatives you've considered

As a workaround you can write Astro middlewares that can make request to s3 buckets for instance. (The problem is mixing responsibilities with this approach)

**Comment by lukeshay** [comment]
@Csszabi98 Could you please provide more info like a link or a repo with an example of what you want?

Right now middleware and `Astro.locals` work so I am not sure what you are requesting.

Thanks you!

**Comment by lukeshay** [comment]
This has been completed.
